name: flutter_template
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.5
  get: ^4.6.6
  http: ^1.1.0
#  google_fonts: ^4.0.4
  page_transition: ^2.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
#  flutter_inappwebview: ^5.4.3+7
  url_launcher: ^6.2.1
  fluttertoast: ^8.2.1
  cached_network_image: ^3.2.3
#  lottie: ^2.3.2
#  shimmer: ^2.0.0
#  image_picker: ^0.8.5+3
#  permission_handler: ^10.1.0
#  dio: ^4.0.6
#  custom_refresh_indicator: ^2.0.1
  flutter_svg: ^2.0.5
#  flutter_svg_provider: ^1.0.3
#  flutter_asset_generator: ^1.1.0
  flutter_launcher_icons: ^0.13.1

flutter_assets_generator:
  auto_detection: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/
    - assets/svgs/
    - assets/images/new/
    - assets/images/AmphionIpadVA1/
    - assets/images/AmphionIpadVA2/
    - assets/images/AmphionIpadVA3/
    - assets/images/AmphionPhysicianVAIpadFinalAW/
    - assets/
    - assets/audios/
    - assets/videos/


flutter_assets:
  assets_path: assets/
  output_path: lib/generated/
  filename: assets.dart
  field_prefix:

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/cover_image.png"